### PR TITLE
feat: add `Tree` component

### PR DESCRIPTION
**Pull request by cheton**
Demo: https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-785/components/tree

## Figma

Dark mode
https://www.figma.com/file/bHr2zAshr0D5ROp8vCVPFR/Tonic---Dark-Mode?node-id=18308%3A118450

Light mode
https://www.figma.com/file/62S1DnH4Pqy1MxJQCcLXUA/Tonic---Light-Mode?node-id=8482%3A74382

## TODOs
- [x] Fix animation delay that occurs when toggling nodes
    - https://github.com/trendmicro-frontend/tonic-ui/pull/785#issuecomment-1676592401
- [x] Enhance rendering performance for a substantial quantity of node (e.g. 100 or more)
- [x] Implement a load on demand example
- [x] Add visual indicators for load on demand
- [x] Show the scrollbar only upon hovering
- [x] Apply bold styling to node labels for selected nodes
- [x] Rename component from `TreeNode` to `TreeItem`
- [x] Enhance "load on demand" mechanism to prevent re-fetching loaded nodes upon toggling expansion state
- [x] Establish connections between tree nodes with connecting lines
- [x] Include a Drag-and-Drop (DnD) demonstration
- [x] Add a basic usage section
- [x] Add icons to the dropdown example
- [ ] Introduce tri-state selection functionality

### CODE REVIEW

**Comment by tinaClin** [comment]
顯示層數時，會有lag的情況

https://github.com/trendmicro-frontend/tonic-ui/assets/24446505/e15e32f8-f9f1-4e25-957e-f2bb96ac76ed

**Comment by tinaClin** [comment]
收合selectable tree時，會有頓頓的情況

https://github.com/trendmicro-frontend/tonic-ui/assets/24446505/61a821cd-b3c5-4bdc-ab49-840533c480d2

**Review by tinaClin — APPROVED** [review]

**Comment by cheton** [comment]
> 顯示層數時，會有lag的情況
> 
>  Screen.Recording.2023-08-10.at.11.25.43.AM.mov

Fixed in https://github.com/trendmicro-frontend/tonic-ui/pull/785/commits/25090954b8194416a8b818d5939ea81be1b1fe7e by setting `appear` to `false` to avoid the enter transition of the first mount

```diff
   <TransitionComponent
-   appear={true}
+   appear={false} // do not perform the enter transition when it first mounts
    in={isExpanded}
    role="group"
    unmountOnExit={true}
```

**Comment by cheton** [comment]
> 收合selectable tree時，會有頓頓的情況
> 
>  Screen.Recording.2023-08-10.at.11.51.56.AM.mov

The delay in expanding the scrollable area of the tree will be acknowledged as a known issue for now. You can use native scrollbar to mitigate this issue.

**Pull request merged**
