### PR TITLE
docs: add collapse code block

### PR DESCRIPTION
**Pull request by austinhung81**
- We will default collapse the editable example code block, except getting start and themes (they are also can not be editable).

Screen Shot 2020-10-14 at 4 46 40 PM

- Also support like below to default expand code block
Screen Shot 2020-10-14 at 4 53 29 PM

- The style of the code block is still working on it, need to discuss with VDs.

### CODE REVIEW

**Comment by cheton** [comment]
How about only keeping the visible collapsed area as illustrated below in red rectangle?

image

**Comment by austinhung81** [comment]
> How about only keeping the visible collapsed area as illustrated below in red rectangle?
> 
> image

I updated the code block style provided by the designer.
Screen Shot 2020-10-19 at 6 19 45 PM

**Comment by cheton** [comment]
It looks much better. The only issue is that the clickable area (arrow icon) is too small to click.

**Comment by tinaClin** [comment]
Please help to change cursor style to `pointer` when hovering the clickable area, thank you.
image

**Comment by austinhung81** [comment]
> It looks much better. The only issue is that the clickable area (arrow icon) is too small to click.

I changed the entire area to trigger the collapse in a hover style, and I will review it with Pin this afternoon.

**Comment by austinhung81** [comment]
> Please help to change cursor style to `pointer` when hovering the clickable area, thank you.
> image

fixed in 098bd65

**Review by roth1002 — APPROVED** [review]

**Comment by austinhung81** [comment]
In 93e2c59
- Removed the background color hover style of the collapsible area.
- Added a height condition to determine whether to use collapse, because if there is only one line of code, as shown below, which is strange.
Screen Shot 2020-10-20 at 6 21 31 PM

**Comment by cheton** [comment]
Just my two cents. We can align with the Accordion's style. The toggler will not lose focus when changing the visibility of the code block.

image

image

**Review by cheton — APPROVED** [review]

**Comment by austinhung81** [comment]
> Just my two cents. We can align with the Accordion's style. The toggler will not lose focus when changing the visibility of the code block.
> 
> image
> 
> image

Hi @cheton,

I've discussed this option with Pin, but on a big screen, it'll be too far to click the arrow. When you look from top to bottom, putting it below may make the user expand the code faster, although I know it will lose focus.
Screen Shot 2020-10-21 at 9 37 04 AM

**Pull request merged**
