### PR TITLE
breaking: refactor Transition components to ensure consistency of transition usage and props

### LINKED ISSUE #295: [Transition] Deprecate the passing function as children usage for transition components in the v1 release
PR #297

### LINKED ISSUE #348: Example: render the toast notification on top of an modal with an animation effect

### PR DESCRIPTION
**Pull request by cheton**
Merge this PR to the master branch only for the v1 release.

### Transitions
https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-297/transitions

### Components
https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-297/accordion
https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-297/drawer
https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-297/menu
https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-297/modal
https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-297/popover
https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-297/tooltip

## What's Changed
* [x] remove `react-spring` dependency
* [x] remove `react-animate-height` dependency
* [x] add `Presence` component and `usePresence` Hook for the exit animation
* [x] export `Popper` component
* [x] export `Presence` component and `usePresence` Hook
* [x] `Popover`: change the `delay` prop to `enterDelay` and `leaveDelay`
* [x] `Tooltip`: rename `showDelay` and `hideDelay` to `enterDelay` and `leaveDelay`
* [x] `Accordion` enhancement
      - **Collapse** transition is internally used in `AccordionPanel`
* [x] `Drawer` enhancement
      - **Fade** transition is internally used in `DrawerOverlay`
      - **Slide** transition is internally used in `DrawerContent`
* [x] `Modal` enhancement
      - **Fade** transition is internally used in `ModalOverlay`
      - **Fade** transition is internally used in `ModalContent`
* [x] `Popover` enhancement
      - **Grow** transition is internally used in `PopoverContent`
* [x] `Tooltip` enhancement
      - **Grow** transition is internally used in `Tooltip`
* [x] Provide the capability to pass transition props to Drawer, Modal, Popover, and Tooltip
     - react-styled-ui
     - styled-ui-docs
* [x] `Menu` enhancement
    - **Collapse** transition is internally used in `MenuList`
    - UI spec: https://www.figma.com/file/zlRHnlL3nAEN3OT1VoRAqM/Interaction?node-id=20469%3A102687
    - [ ] Context menu (https://mui.com/components/menus/#context-menu)
* [ ] `Badge` component

## Overview
* [x] **Collapse** (internally used in `Accordion` and `Menu`)
* [x] **Fade** (internally used in `Modal`)
* [x] **Grow** (internally used in `Tooltip` and `Popover`)
* [x] **Scale**
* [x] **Slide** (internally used in `Drawer`)
* [x] **Zoom**

### Easing

| Name | Value | Description |
| :--- | :---- | :---------- |
| easeInOut | `cubic-bezier(0.4, 0, 0.2, 1)` | This is the most common easing curve. |
| easeOut | `cubic-bezier(0.0, 0, 0.2, 1)` | Objects enter the screen at full velocity from off-screen and slowly decelerate to a resting point. |
| easeIn | `cubic-bezier(0.4, 0, 1, 1)` | Objects leave the screen at full velocity. They do not decelerate when off-screen. |
| sharp | `cubic-bezier(0.4, 0, 0.6, 1)` | The sharp curve is used by objects that may return to the screen at any time. |

### Timeout

| Name | Value | Description |
| :--- | :---- | :---------- |
| shortest | 150ms | |
| shorter | 200ms | |
| short | 250ms | |
| standard | 300ms | most basic recommended timing |
| enteringScreen | 225ms | recommended when something is entering screen |
| leavingScreen | 195ms | recommended when something is leaving screen |

### Transition within Components

| Transition | Components |
| :-- | :-- |
| Collapse | `Accordion`, `Menu` |
| Fade | `Modal` |
| Grow | `Tooltip`, `Popover` |
| Scale | |
| Slide | `Drawer` |
| Zoom | |

### Transiton Easing & Timeout

| Transition | Enter Easing | Exit Easing | Enter Timeout | Exit Timeout |
| :-- | :-- | :-- | :-- | :-- |
| Collapse | easeInOut | easeInOut | standard (300ms) | standard (300ms) |
| Fade | easeInOut | easeInOut | enteringScreen (225ms) | leavingScreen (195ms) |
| Grow | easeInOut | easeInOut | 'auto' | 'auto' |
| Scale | easeOut | easeIn | 150ms | 150ms |
| Slide | easeOut | sharp | enteringScreen (225ms) | leavingScreen (195ms) |
| Zoom | easeInOut | easeInOut | enteringScreen (225ms) | leavingScreen (195ms) |

### Transition Style

| Transition | Entering | Entered | Exiting | Exited |
| :-- | :-- | :-- | :-- | :-- |
| Collapse | <pre>heght: auto;</pre> | <pre>heght: auto;</pre> | <pre>height: 0;<br>overflow: hidden;</pre> | <pre>height: 0;</pre> |
| Fade | <pre>opacity: 1;</pre> | <pre>opacity: 1;</pre> | <pre>opacity: 0;</pre> | <pre>opacity: 0;</pre> |
| Grow | <pre>opacity: 1;<br>transform: scale(1, 1);</pre> | <pre>opacity: 1;<br>transform: none;</pre> | <pre>opacity: 0;<br>transform: scale(0.75, 0.5625);</pre><sup>`Note: 0.75 x 0.75 = 0.5625`</sup> | <pre>opacity: 0;<br>transform: scale(0.75, 0.5625);</pre><sup>`Note: 0.75 x 0.75 = 0.5625`</sup> |
| Scale | <pre>transform: none;</pre> | <pre>transform: none;</pre> | <pre>transform: scale(0.95, 0.95);</pre> | <pre>transform: scale(0.95, 0.95)</pre> |
| Slide | <pre>transform: none;</pre> | <pre>transform: none;</pre> | <pre>transform: translateX(+100%); // LEFT<br>transform: translateX(-100%); // RIGHT<br>transform: translateY(+100%); // UP<br>transform: translateY(-100%); // DOWN</pre> | <pre>transform: translateX(+100%); // LEFT<br>transform: translateX(-100%); // RIGHT<br>transform: translateY(+100%); // UP<br>transform: translateY(-100%); // DOWN</pre> |
| Zoom | <pre>transform: none;</pre> | <pre>transform: none;</pre> | <pre>transform: scale(0);</pre> | <pre>transform: scale(0);</pre> |

## Reference - Material UI
* https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/styles/createTransitions.js
* https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/transitions/utils.js
* https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Collapse/Collapse.js
* https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Fade/Fade.js
* https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Grow/Grow.js
* https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Slide/Slide.js
* https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Zoom/Zoom.js

### CODE REVIEW

**Comment by tinaClin** [comment]
`Tooltip`有一個範例(Tooltip with Menu)壞掉了

Tooltip-issue

@cheton: fixed in https://github.com/trendmicro-frontend/styled-ui/pull/297/commits/8331741e070694d1428bd017206fa4b03a007075

**Comment by tinaClin** [comment]
另外發現一個問題，`Checkbox`在`focus`狀態，style有跑掉....
image

@cheton: fixed in https://github.com/trendmicro-frontend/styled-ui/pull/297/commits/8331741e070694d1428bd017206fa4b03a007075

**Comment by tinaClin** [comment]
`Popover`不會自動消失
image

@cheton: fixed in https://github.com/trendmicro-frontend/styled-ui/pull/297/commits/963ed5d4fe4b33663c2a37f5ecd14d283399dc44

**Comment by cheton** [comment]
@tinaClin The issue of missing initial focus on the popover content was resolved in https://github.com/trendmicro-frontend/styled-ui/pull/297/commits/963ed5d4fe4b33663c2a37f5ecd14d283399dc44

**Comment by tinaClin** [comment]
`Toast`沒有跳
image

@cheton: fixed in https://github.com/trendmicro-frontend/styled-ui/pull/297/commits/a626e3366cc0b46c643d961203ef896dd22b7793

**Comment by tinaClin** [comment]
有些頁面的Button，在點擊第2個按鈕時，畫面會抖動
buttons


@cheton: fixed in https://github.com/trendmicro-frontend/styled-ui/pull/297/commits/7c0261bfc1b20150dc48a5b6bcab9eb64915393f

@tinaClin: fixed in https://github.com/trendmicro-frontend/styled-ui/commit/1a13600c602c6d1d8d64bdbaf4f0f190085dcc75

**Comment by cheton** [comment]
Fixed a bug that cannot show toast notification on the ui (a626e33)

**Review by tinaClin — APPROVED** [review]

**Pull request merged**
