### PR TITLE
feat: expose 'backdropProps' to ModalContent passing into ModalContentBackdrop

### PR DESCRIPTION
**Pull request by light049**
## Descriptions
Requirement to have a modal without scrolling inside modal body, when dynamic content that exceeds window's height, the exceeding parts would need scroll to view.
<kbd></kbd>

## Changes
Expose a prop 'backdropProps' to ModalContent passing needed props into ModalContentBackdrop.

**Usage sample:**
```
...
  <ModalContent maxHeight='none' backdropProps={{overflowY: 'auto'}}>
    ...
    <ModalBody overflowY='visible'>
      ...dynamic content that might exceed viewport height
    </ModalBody>    
    ...
  </ModalContent>
...
```

### CODE REVIEW

**Comment by cheton** [comment]
@light049 We're considering a another approach by adding a `backdrop` prop (defaults to `true` for the modal) as well as the one used in `Drawer`. When `backdrop` is disabled, you can wrap the modal content using a custom-made component rather than override default backdrop style.

Please stay tuned for the further update.

**Comment by light049** [comment]
@cheton Agree, it seems reasonable since the ModalContentBackdrop is an internal component. Thanks for your reply~

**Comment by cheton** [comment]
> @cheton Agree, it seems reasonable since the ModalContentBackdrop is an internal component. Thanks for your reply~

@light049 Your solution is by far the most simple way to work around it. Please allow me to spend a couple of days thinking about the component structure.

**Comment by cheton** [comment]
https://chakra-ui.com/docs/components/overlay/modal#modal-overflow-behavior

### [Modal overflow behavior](https://chakra-ui.com/docs/components/overlay/modal#modal-overflow-behavior)

If the content within the modal overflows beyond the viewport, you can use the `scrollBehavior` to control how scrolling should happen.

* If set to `inside`, scroll only occurs within the `ModalBody`.
* If set to `outside`, the entire `ModalContent` will scroll within the viewport.

**Comment by light049** [comment]
> https://chakra-ui.com/docs/components/overlay/modal#modal-overflow-behavior
> 
> ### [Modal overflow behavior](https://chakra-ui.com/docs/components/overlay/modal#modal-overflow-behavior)
> If the content within the modal overflows beyond the viewport, you can use the `scrollBehavior` to control how scrolling should happen.
> 
> * If set to `inside`, scroll only occurs within the `ModalBody`.
> * If set to `outside`, the entire `ModalContent` will scroll within the viewport.

This seems fine to be an option too, and the `backdrop` could still exist for further custom needs. 😃

**Comment by cheton** [comment]
The new scrolling behavior be added on PR #515 

For this PR, I would like to add two props to `ModalContent` just like `TransitionComponent` and `TransitionProps`
* `ContainerComponent`
* `ContainerProps`

**Comment by cheton** [comment]
As PR #515 has completely resolved this issue and a `ModalContainer` component will be exported for experimental use. I will close this PR unless we see any chances for making improvement in the future.

**Comment by cheton** [comment]
Published [v1.0.0-beta.0](https://www.npmjs.com/package/@tonic-ui/react/v/1.0.0-beta.0)

**Pull request closed without merging**
