### PR TITLE
feat: add ButtonGroup component

### PR DESCRIPTION
**Pull request by tinaClin**
# ButtonGroup

ButtonGroup is used to group related buttons.

image
image
image

## Import

```js
import ButtonGroup from '@trendmicro/react-styled-core/ButtonGroup';
// or
import { ButtonGroup } from '@trendmicro/react-styled-core';
```

## Usage

```jsx
<ButtonGroup>
  <Button>One</Button>
  <Button>Two</Button>
</ButtonGroup>
```

### Direction

Make a set of buttons appear vertically stacked rather than horizontally, by adding `vertical` to the `<ButtonGroup>`.

```jsx
<>
  <ButtonGroup>
    <Button>One</Button>
    <Button>Two</Button>
    <Button>Three</Button>
  </ButtonGroup>
  <Space width="1rem" />
  <ButtonGroup vertical>
    <Button>One</Button>
    <Button>Two</Button>
    <Button>Three</Button>
  </ButtonGroup>
</>
```

### Buttons Variant

Use the `variant` prop to change the visual style of every button in a group. You can set the value to `solid`, `outline`. Use `outline` to remove all background images and colors on any button.

```jsx
<>
  <ButtonGroup variant="solid">
    <Button>One</Button>
    <Button>Two</Button>
  </ButtonGroup>
  <Space width="1rem" />
  <ButtonGroup variant="outline">
    <Button>One</Button>
    <Button>Two</Button>
  </ButtonGroup>
</>
```

### Buttons Color

Use the `variantColor` prop to change the color scheme of every button in a group. `variantColor` can be any color key with key `50`(hover), `60`(normal) and `70`(active) that exist in the `theme.color`.

```jsx
<ButtonGroup variantColor="blue">
  <Button>Left</Button>
  <Button>Middle</Button>
  <Button>Right</Button>
</ButtonGroup>
```

### Buttons Size

Use the `size` prop to change the size of every button in a group. You can set the value to `sm`, `md`, or `lg`.

```jsx
<Stack spacing="1rem">
  <ButtonGroup size="sm">
    <Button>Left</Button>
    <Button>Middle</Button>
    <Button>Right</Button>
  </ButtonGroup>
  <ButtonGroup size="md">
    <Button>Left</Button>
    <Button>Middle</Button>
    <Button>Right</Button>
  </ButtonGroup>
  <ButtonGroup size="lg">
    <Button>Left</Button>
    <Button>Middle</Button>
    <Button>Right</Button>
  </ButtonGroup>
</Stack>
```

### Enable Button

```jsx
<>
  <Stack direction="row" spacing="1rem">
    <ButtonGroup>
      <Button><TMIcon name="chart-pie" /></Button>
      <Button><TMIcon name="chart-line" /></Button>
      <Button><TMIcon name="chart-bar" /></Button>
    </ButtonGroup>
    <ButtonGroup>
      <Button>Left</Button>
      <Button>Middle</Button>
      <Button>Right</Button>
    </ButtonGroup>
  </Stack>

  <Space height="1rem" />

  <Stack direction="row" spacing="1rem">
    <ButtonGroup variant="outline">
      <Button><TMIcon name="chart-pie" /></Button>
      <Button><TMIcon name="chart-line" /></Button>
      <Button><TMIcon name="chart-bar" /></Button>
    </ButtonGroup>
    <ButtonGroup variant="outline">
      <Button>Left</Button>
      <Button>Middle</Button>
      <Button>Right</Button>
    </ButtonGroup>
  </Stack>
</>
```

### Selected Button

```jsx
<>
  <Stack direction="row" spacing="1rem">
    <ButtonGroup>
      <Button active><TMIcon name="chart-pie" /></Button>
      <Button><TMIcon name="chart-line" /></Button>
      <Button><TMIcon name="chart-bar" /></Button>
    </ButtonGroup>
    <ButtonGroup>
      <Button active>Left</Button>
      <Button>Middle</Button>
      <Button>Right</Button>
    </ButtonGroup>
  </Stack>

  <Space height="1rem" />

  <Stack direction="row" spacing="1rem">
    <ButtonGroup variant="outline">
      <Button active><TMIcon name="chart-pie" /></Button>
      <Button><TMIcon name="chart-line" /></Button>
      <Button><TMIcon name="chart-bar" /></Button>
    </ButtonGroup>
    <ButtonGroup variant="outline">
      <Button active>Left</Button>
      <Button>Middle</Button>
      <Button>Right</Button>
    </ButtonGroup>
  </Stack>
</>
```

### Disabled Button

```jsx
<>
  <Stack direction="row" spacing="1rem">
    <ButtonGroup>
      <Button><TMIcon name="chart-pie" /></Button>
      <Button><TMIcon name="chart-line" /></Button>
      <Button disabled><TMIcon name="chart-bar" /></Button>
    </ButtonGroup>
    <ButtonGroup>
      <Button>Left</Button>
      <Button>Middle</Button>
      <Button disabled>Right</Button>
    </ButtonGroup>
  </Stack>

  <Space height="1rem" />

  <Stack direction="row" spacing="1rem">
    <ButtonGroup variant="outline">
      <Button><TMIcon name="chart-pie" /></Button>
      <Button><TMIcon name="chart-line" /></Button>
      <Button disabled><TMIcon name="chart-bar" /></Button>
    </ButtonGroup>
    <ButtonGroup variant="outline">
      <Button>Left</Button>
      <Button>Middle</Button>
      <Button disabled>Right</Button>
    </ButtonGroup>
  </Stack>
</>
```

## Props

The ButtonGroup composes the `Box` component so you can pass props for `Box`. These are props related to the ButtonGroup component.

| Name | Type | Default | Description |
| :--- | :--- | :------ | :---------- |
| `size` | `sm`, `md`, `lg` | `md` | Sets the size for all Buttons in the group. |
| `variant` | `solid`, `outline` | `solid` | Sets the variant of all Buttons in the group. |
| `variantColor` | string | | Sets the variant of all Buttons in the group. Use a color key passed in `theme.colors`. |
| `vertical` | boolean | `false` | Make the set of Buttons appear vertically stacked. |

### CODE REVIEW

**Comment by cheton** [comment]
`packages/styled-docs/pages/buttonGroup.mdx` 要 rename 成 `buttongroup.mdx`，因為你的 macOS 的 fs 是用  case-insensitive 所以沒遇到這個 bug 😆 

Resolved by https://github.com/trendmicro-frontend/styled-ui/pull/34/commits/087f7e30e163c06612d1f44db2f4a16e656d07e9

**Comment by cheton** [comment]
The purpose of ButtonGroup is to group buttons without spacing between them. I don't think it necessary to provide the `isAttached` prop.

image


#### Real world examples

https://material-ui.com/components/button-group/#group-sizes-and-colors
https://react-bootstrap.github.io/components/button-group/
https://reactstrap.github.io/components/button-group/
https://react-native-elements.github.io/react-native-elements/docs/button_group.html

**Review by cheton — CHANGES_REQUESTED** [review]
Suggest using a transparent border as the base, and apply border color for each variant. When hovering over a button, use `box-shadow` to display the hover effect.

**Comment by tinaClin** [comment]
> The purpose of ButtonGroup is to group buttons without spacing between them. I don't think it necessary to provide the `isAttached` prop.
> 
> image
> 
> #### Real world examples
> https://material-ui.com/components/button-group/#group-sizes-and-colors
> https://react-bootstrap.github.io/components/button-group/
> https://reactstrap.github.io/components/button-group/
> https://react-native-elements.github.io/react-native-elements/docs/button_group.html

Fixed in https://github.com/trendmicro-frontend/styled-ui/pull/34/commits/e6b9da527fdb9b51b7af93c8ee7e716c989da0b4

**Comment by tinaClin** [comment]
> Suggest using a transparent border as the base, and apply border color for each variant. When hovering over a button, use `box-shadow` to display the hover effect.

Fixed in https://github.com/trendmicro-frontend/styled-ui/pull/34/commits/4116a50ced2cb590b46ec5d3ed1a3cf076860897

**Review by cheton — APPROVED** [review]

**Comment by cheton** [comment]
@tinaClin I revised some wordings at here:
https://github.com/trendmicro-frontend/styled-ui/blob/7be83117c8fbe0a8df0e8d9208a1153e8b941d81/packages/styled-docs/pages/buttongroup.mdx

**Comment by cheton** [comment]
Note that [button.mdx](https://github.com/trendmicro-frontend/styled-ui/blob/7be83117c8fbe0a8df0e8d9208a1153e8b941d81/packages/styled-docs/pages/button.mdx) is not completed yet.

**Pull request merged**
