### PR TITLE
feat(react/Calendar): enhance keyboard navigation and date selection

### LINKED ISSUE #904: Add tabbing focus support to `Calendar` and `DatePicker` components
Currently, the `Calendar` and `DatePicker` components only support `focus-visible` state for the `Previous month` and `Next month` arrow buttons. Current implementation does not support tabbing focus for date selection, which can impact keyboard navigation and accessibility.

image

image

### PR DESCRIPTION
**Pull request by cheton**
Demo: https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-909/components/date-pickers/calendar

### New Updates
- [x] Use `ArrowLeft`, `ArrowRight`, `ArrowUp`,  `ArrowDown`, `Home`, and `End` keys to navigate between days in month view.
- [x] When pressing `TAB` or `TAB` + `SHIFT` to navigate from outside the calendar into it, the focus should be set to today’s date or the specified selected date.
- [x] Enable date selection with `SPACE` or `ENTER` keys'
- [x] Add support for year selection with keyboard navigation

### Operation Keys
* Forward navigation: Press `Tab`
* Backward navigation: Press `Shift` + `Tab`
* Month selection (⬅️➡️): Press `Space` or `Enter` on the arrow buttons (⬅️➡️)
* Year selection (⬆️⬇️): Press `ArrowUp` or `ArrowDown` keys to increase or decrease current year
* Day selection
  - Press ⬅️➡️⬆️⬇️ to navigate between days
  - Press `Enter` or `Space` to select date.
  - Note: Deselecting is supported for the Calendar view, but not implemented in the demo.

### CODE REVIEW

**Comment by tinaClin** [comment]
@cheton  There is a side effect: when I try to select a date for the next month (September 20), the Calendar UI jumps back to the current month (August).

https://github.com/user-attachments/assets/b34b9ed6-87ba-4b62-a1d2-9597dee4bacf

**Comment by cheton** [comment]
> @cheton There is a side effect: when I try to select a date for the next month (September 20), the Calendar UI jumps back to the current month (August).
> 
>  Screen.Recording.2024-08-19.at.9.50.41.AM.mov

@tinaClin 
The focus handling regression was resolved in https://github.com/trendmicro-frontend/tonic-ui/pull/909/commits/b88001dba44994a9fa59a5018367f9c214f0546e

**Comment by cheton** [comment]
@tinaClin I updated the code to manage the focus change exclusively for the "Tab" key (https://github.com/trendmicro-frontend/tonic-ui/pull/909/commits/d5fa7195cb7ec16392157212bc3d9c99e20d85eb)

**Comment by cheton** [comment]
@trend-albert-shala Could you help check the keyboard navigation behavior in the [demo](https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-909/components/date-pickers/calendar)?

**Comment by trend-albert-shala** [comment]
> Operation Keys

@cheton the changes look good, tested the options outlined under Operation Keys, and they're working as expected. Btw I'm on a Mac, if additional testing on a Windows machine is needed

**Review by tinaClin — APPROVED** [review]

**Review by trend-albert-shala — APPROVED** [review]

**Comment by cheton** [comment]
> @cheton the changes look good, tested the options outlined under Operation Keys, and they're working as expected. Btw I'm on a Mac, if additional testing on a Windows machine is needed

Thank you for confirming. We have tested it on both Windows and Mac, using Chrome and Safari browsers.

For Safari, users will need to enable "Tab" navigation first:
1. Open the Safari browser on your Mac
2. Go to "Safari > Preferences > Advanced"
3. Check the option `Press Tab to highlight each item on a webpage` to enable tab navigation

**Pull request merged**
