### PR TITLE
feat: Add typescript declaration file

### PR DESCRIPTION
**Pull request by RossThomson**
This adds all the typescript types that we have created for the components we have used at conformity so far.
It does not cover all components but it is a good start and can be added to as needed.

### CODE REVIEW

**Review by joshuatai — COMMENTED** [review]
Hi @RossThomson,

Thank you for your contribution! Regarding the TypeScript declaration file of the Styled UI, since the Styled UI is developed based on the Styled-System, it is recommended that you first set the npm package - "@types/styled-system" up in the tsconfig file, and then just define the specific part of Styled UI. The advantage is that the declaration file provided by @DefinitelyTyped is very reliable and stable, and more developers can provide feedback and quick updates.

npm package: 
https://www.npmjs.com/package/@types/styled-system
https://www.npmjs.com/package/@types/styled-system__core
https://www.npmjs.com/package/@types/styled-system__should-forward-prop
https://www.npmjs.com/package/@types/styled-system__css
https://www.npmjs.com/package/@types/styled-system__theme-get

GitHub repo: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e9d633263c181bfe98e7f90bab675588fb454f06/types/styled-system/index.d.ts

**Comment by QuentinDejean** [comment]
Hey @joshuatai ! Thanks for coming back to us!

We were not aware that `styled-ui` was based off a different design system. we're happy to take a look at it, it may take us a while to get there however.

**Comment by joshuatai** [comment]
Hi @RossThomson,

BTW, Styled System is a collection of utility functions (base on a CSS-in-JS library, such as Styled components or emotion) that add style props to React components and control styles based on a global theme object with typographic scales, colors, and layout properties. [Styled Components](https://styled-system.com/) is for your reference.

**Comment by cheton** [comment]
In short, we don't have plan to maintain type definition file in this repo for this moment, unless we have a systematic way for automating the process.

**Pull request closed without merging**
